partyDescriptions = {
    "PvdD": "U plaatst de belangen van een leefbare Aarde, dieren en natuur radicaal voorop. Dit betekent een snelle en forse krimp van de vee-industrie, een einde aan fossiele subsidies en een verbod op kernenergie. U bent voorstander van het verankeren van dierenrechten en rechten voor de natuur in de Grondwet. U kiest voor een eerlijke verdeling van welvaart, met hogere belastingen op grote vermogens en vervuiling, en een humaan migratiebeleid.",
    "BBB": "U staat pal voor de Nederlandse boeren, tuinders en vissers, die u ziet als de ruggengraat van onze voedselvoorziening en het landschap. U kiest voor een nuchtere aanpak van klimaat- en stikstofproblemen ('Wie rood staat, kan niet groen doen') en verzet zich tegen gedwongen uitkoop van boeren. U hecht veel waarde aan de regio, 'noaberschap', Nederlandse tradities en een overheid die dichtbij de mensen staat.",
    "CDA": "U kiest voor een fatsoenlijk land, gebouwd op vertrouwen, verantwoordelijkheid en een betrokken samenleving. U zoekt een balans tussen een sterke, duurzame economie en een zorgzame gemeenschap. U pleit voor een streng maar werkbaar migratiebeleid, een eenvoudiger belastingstelsel en het behoud van de hypotheekrenteaftrek in aangepaste vorm.",
    "CU": "U benadert de politiek vanuit christelijk-sociale waarden, met de nadruk op gemeenschappen, het gezin en de bescherming van het (ongeboren) leven. U bent voor ambitieus klimaatbeleid, zorg voor de schepping en een humaan migratiebeleid, maar ook voor een streng en realistisch asielbeleid. Financieel wilt u gezinnen ondersteunen en de grootste vermogens extra belasten.",
    "D66": "U streeft naar een progressief en vrij Nederland in een sterk en verenigd Europa. U bent voor ambitieuze klimaatdoelen, meer investeringen in schone energie en een toekomst voor zowel boeren als natuur. U hecht veel waarde aan gelijke kansen, LHBTIQA+-rechten en een sterke, weerbare democratie. U wilt de woningnood doorbreken met de bouw van tien nieuwe steden.",
    "DENK": "De strijd tegen discriminatie en racisme is voor u een topprioriteit. U pleit voor wederzijdse acceptatie in plaats van eenzijdige aanpassing en wilt dat het woord 'integratie' wordt afgeschaft voor wie hier is opgegroeid. U wilt de koopkracht verbeteren door de btw op boodschappen te verlagen en het eigen risico af te schaffen. Internationaal komt u op voor de rechten van de Palestijnen.",
    "FvD": "U wilt Nederland weer soeverein, vrij en trots maken. Dit betekent een Nexit, het opzeggen van internationale verdragen en het stoppen met alle klimaat- en stikstofbeleid. U pleit voor het heropenen van het Groninger gasveld voor betaalbare energie en een radicale verlaging van de belastingen. U wilt meer directe democratie via bindende referenda.",
    "GroenLinks-PvdA": "U gelooft in solidariteit en het eerlijk delen van welvaart in een groene en duurzame toekomst. U wilt de klimaatcrisis ambitieus aanpakken, grote vervuilers laten betalen en de fossiele subsidies afschaffen. U streeft naar een 'Nieuwe Verzorgingsstaat' met hogere lonen, betaalbare woningen en een sterke publieke sector. U staat voor een humaan migratiebeleid en een sterke, sociale Europese Unie.",
    "JA21": "U kiest voor een conservatief-liberale koers met een focus op veiligheid, welvaart en grenzen. U wilt migratie sterk beperken, met als doel een asielstop, en internationale verdragen herzien. U bent voor een kleinere overheid, lagere belastingen en een harde aanpak van criminaliteit. Het beschermen van de eigen woning tegen extra belastingen is voor u belangrijk.",
    "PVV": "U wilt de Nederlander weer op 1 zetten. Een totale asielstop en het sluiten van de grenzen is uw topprioriteit, desnoods door verdragen op te zeggen. U wilt de Klimaatwet intrekken, de btw op energie en boodschappen verlagen en het eigen risico afschaffen. U wilt de Nederlandse cultuur en tradities, inclusief Zwarte Piet, beschermen en de invloed van de islam terugdringen.",
    "SP": "U streeft naar een 'super sociaal' Nederland, waarin de belangen van de werkende klasse voorop staan. U wilt een einde aan marktwerking in de publieke sector: het eigen risico moet af, wonen moet een recht zijn en het openbaar vervoer wordt gratis. U pleit voor een forse verhoging van het minimumloon naar €18 en een sociale klimaatrevolutie.",
    "NSC": "U wilt de basis op orde brengen met een betrouwbare overheid en bestaanszekerheid. U kiest voor een streng en realistisch migratiebeleid op alle vlakken en een oplossing voor de stikstofcrisis die boeren perspectief biedt, zonder gedwongen uitkoop. Een eenvoudiger en eerlijker belasting- en toeslagenstelsel en het oplossen van de wooncrisis zijn voor u cruciale punten.",
    "VVD": "U staat voor een land met vrijheid, veiligheid en welvaart. U wilt radicale economische groei, een kleinere overheid en u beschermt eigenwoningbezit. De partij pleit voor een strenger asielstelsel om meer grip op migratie te krijgen en voor een sterke, innovatieve economie met een aantrekkelijk vestigingsklimaat.",
    "Volt": "U gelooft in een sterk en federaal Europa als antwoord op de grote uitdagingen van deze tijd. U pleit voor een Europese krijgsmacht, een gezamenlijk en ambitieus klimaatbeleid en een humaan Europees asielbeleid. U wilt investeren in een 'Silicon Europa' om technologisch onafhankelijk te zijn en bent voorstander van een basisinkomen.",
    "SGP": "U baseert uw politiek op **christelijke waarden en normen, met de Bijbel als een betrouwbaar en tijdloos kompas**. U ziet het **klassieke gezin als het fundament van een gezonde samenleving** en komt op voor **het kwetsbare leven**, van het ongeboren kind tot de broze oudere. Veiligheid is een prioriteit, met een sterke krijgsmacht en een harde aanpak van criminaliteit. U wilt een **volledige stop op immigratie uit Afrika en het Midden-Oosten en remigratie aanmoedigen**. Daarnaast wilt u een einde aan het klimaat- en stikstofbeleid, de gaswinning in Groningen hervatten en inzetten op kernenergie. U streeft naar een **kleinere overheid, lagere belastingen en het herwinnen van soevereiniteit door een Nexit**."
}
