partyDescriptions = {
    "PvdD": "You radically prioritize the interests of a livable Earth, animals, and nature. This means a rapid and substantial reduction of the livestock industry, an end to fossil subsidies, and a ban on nuclear energy. You advocate for enshrining animal rights and rights for nature in the Constitution. You opt for a fair distribution of wealth, with higher taxes on large fortunes and pollution, and a humane migration policy.",
    "BBB": "You stand firmly for Dutch farmers, growers, and fishermen, whom you see as the backbone of our food supply and landscape. You opt for a down-to-earth approach to climate and nitrogen problems ('You can't be green if you're in the red') and oppose the forced buyout of farmers. You highly value the region, 'noaberschap' (neighborliness), Dutch traditions, and a government that is close to the people.",
    "CDA": "You choose a decent country, built on trust, responsibility, and an engaged society. You seek a balance between a strong, sustainable economy and a caring community. You advocate for a strict but workable migration policy, a simpler tax system, and the preservation of the mortgage interest deduction in a modified form.",
    "CU": "You approach politics from Christian-social values, with an emphasis on communities, the family, and the protection of (unborn) life. You are in favor of an ambitious climate policy, care for creation, and a humane migration policy, but also a strict and realistic asylum policy. Financially, you want to support families and impose extra taxes on the largest fortunes.",
    "D66": "You strive for a progressive and free Netherlands in a strong and united Europe. You are in favor of ambitious climate goals, more investment in clean energy, and a future for both farmers and nature. You highly value equal opportunities, LGBTQIA+ rights, and a strong, resilient democracy. You want to break the housing crisis by building ten new cities.",
    "DENK": "The fight against discrimination and racism is a top priority for you. You advocate for mutual acceptance instead of one-sided adaptation and want the word 'integration' to be abolished for those who have grown up here. You want to improve purchasing power by lowering VAT on groceries and abolishing the healthcare deductible. Internationally, you stand up for the rights of the Palestinians.",
    "FvD": "You want to make the Netherlands sovereign, free, and proud again. This means a Nexit, terminating international treaties, and stopping all climate and nitrogen policies. You advocate for reopening the Groningen gas field for affordable energy and a radical reduction in taxes. You want more direct democracy through binding referendums.",
    "GroenLinks-PvdA": "You believe in solidarity and the fair sharing of wealth in a green and sustainable future. You want to tackle the climate crisis ambitiously, make big polluters pay, and abolish fossil subsidies. You strive for a 'New Welfare State' with higher wages, affordable housing, and a strong public sector. You stand for a humane migration policy and a strong, social European Union.",
    "JA21": "You opt for a conservative-liberal course with a focus on security, prosperity, and borders. You want to severely restrict migration, aiming for a stop to asylum, and revise international treaties. You are for a smaller government, lower taxes, and a tough approach to crime. Protecting homeownership from extra taxes is important to you.",
    "PVV": "You want to put the Dutch people first again. A complete stop to asylum and closing the borders is your top priority, even if it means terminating treaties. You want to repeal the Climate Act, lower VAT on energy and groceries, and abolish the healthcare deductible. You want to protect Dutch culture and traditions, including Zwarte Piet, and push back the influence of Islam.",
    "SP": "You strive for a 'super social' Netherlands, where the interests of the working class come first. You want an end to market forces in the public sector: the healthcare deductible must go, housing must be a right, and public transport will be free. You advocate for a sharp increase in the minimum wage to €18 and a social climate revolution.",
    "NSC": "You want to get the basics in order with a reliable government and security of existence. You opt for a strict and realistic migration policy on all fronts and a solution to the nitrogen crisis that offers farmers perspective, without forced buyouts. A simpler and fairer tax and benefits system and solving the housing crisis are crucial points for you.",
    "VVD": "You stand for a country with freedom, security, and prosperity. You want radical economic growth, a smaller government, and you protect homeownership. The party advocates for a stricter asylum system to get more grip on migration and for a strong, innovative economy with an attractive business climate.",
    "Volt": "You believe in a strong and federal Europe as the answer to the great challenges of our time. You advocate for a European armed forces, a joint and ambitious climate policy, and a humane European asylum policy. You want to invest in a 'Silicon Europe' to be technologically independent and are a proponent of a basic income."
};
